name: 'Versioning Pull Request'
description: 'Issue a pull request for increasing the node package version.'
inputs:
  version-type:
    description: >-
      The type of the semver version. Accepted inputs: major, minor, patch.
    required: true
    default: patch
  prerelease:
    description: >-
      A boolean indicator for creating a prerelease. GitHub 'pre-release' flag will also be set
      accordingly. Accepted inputs: true, false.
    required: false
    default: 'false'
  pre_id:
    description: >-
      A valid semver pre-release id to bump version to a pre-release version with the specific id.
    required: false
  pr-base-branch:
    description: >-
      The base branch that the pull request is issued against.
    required: true
    default: main
  pr-template-uri:
    description: >-
      The FQDN of the uri of the pull request template to be used. Template format can be
      found in: examples.
    required: false
  pr-title:
    description: >-
      The title for the pull request. If pr-template-uri is also used, this parameter will override.
    required: false
  pr-body:
    description: >-
      The body for the pull request. If pr-template-uri is also used, this parameter will override.
    required: false
  pr-reviewers:
    description: >-
      A comma-separated list of the reviewers for the pull request.
      If pr-template-uri is also used, this parameter will override.
    required: false
  pr-team-reviewers:
    description: >-
      A comma-separated list of the team reviewers for the pull request.
      If pr-template-uri is also used, this parameter will override.
    required: false
  pr-labels:
    description: >-
      A comma-separated list of labels to be added to the pull request.
    required: false
    default: 'versioning-pr'
  pr-update-if-exist:
    description: >-
      A boolean indicator for the behavior of re-issuing a pull request from the same branch
      to the same base. If set 'true', it will update the pull request,
      otherwise, action will fail.
    required: true
    default: 'true'
outputs:
  base-branch:
    description: The base branch for this pull request.
  incoming-branch:
    description: The incoming branch for this pull request.
  old-version:
    description: The current version found in the package.json on the base branch.
  new-version:
    description: The new version.
  new-tag:
    description: The new tag.
  versioning-cmd:
    description: The final npm versioning command that is applied.
runs:
  using: 'node12'
  main: 'dist/bin/index.js'
