name: 'Create versioning pull request'
description: 'Create a pull request for increasing the node package version.'
inputs:
  base-branch:
    description: >-
      The base branch that the pull request is issued against.
    required: true
    default: main
  prerelease:
    description: >-
      A boolean indicator for creating a prerelease. GitHub 'pre-release' flag will also be set
      accordingly. Accepted inputs: true, false.
    required: false
    default: 'false'
  pr-create-draft:
    description: >-
      A boolean indicator for whether create a draft pull request or actual one.
    required: false
    default: 'false'
  pr-fail-if-exist:
    description: >-
      A boolean indicator for the behavior of re-issuing a pull request from the same branch
          to the same base. If set 'true', the action will fail.
    required: false
    default: 'true'
  pr-template-uri:
    description: >-
      The FQDN of the uri of the pull request template to be used. Template format can be
      found in: examples.
    required: false
    default: examples/pr-template.yml
  pr-title:
    description: >-
      The title for the pull request. If pr-template-uri is also used, this parameter will override.
    required: false
  pr-description:
    description: >-
      The description for the pull request. If pr-template-uri is also used, this parameter will override.
    required: false
  pr-assignees:
    description: >-
      A comma-separated list of the assignees (usernames) for the pull request.
      If pr-template-uri is also used, this parameter will override the 'assignees' field in the template.
      If none should be set, giving a single comma as value to this field.
      Only users with push access can add assignees to an issue. Assignees are silently ignored otherwise.
    required: false
  pr-reviewers:
    description: >-
      A comma-separated list of the reviewers (usernames) for the pull request.
      If pr-template-uri is also used, this parameter will override the 'reviewers' field in the template.
      If none should be set, giving a single comma as value to this field.
    required: false
  pr-team-reviewers:
    description: >-
      A comma-separated list of the team reviewers (usernames) for the pull request.
      If pr-template-uri is also used, this parameter will override the 'team-reviewers' field in the template.
      If none should be set, giving a single comma as value to this field.
    required: false
  pr-labels:
    description: >-
      A comma-separated list of labels to be added to the pull request.
      If pr-template-uri is also used, this parameter will override the 'labels' field in the template.
      If none should be set, giving a single comma as value to this field.
    required: false
    default: 'versioning-pr'
outputs:
  base-branch:
    description: The base branch for this pull request.
  head-branch:
    description: The head branch for this pull request.
  base-version:
    description: The version found in the package.json on the base branch.
  head-version:
    description: The version found in the package.json on the head branch.
  is-prerelease:
    description: A boolean indicator for the intension for the GitHub release 'prerelease' flag.
  is-pr-draft:
    description: A boolean indicator for the draft pull request.
  pull-request-url:
    description: The new pull request url.
  pull-request-number:
    description: The new pull request number.
  assignees:
    description: The comma-separated list of assignees to the new pull request.
  reviewers:
    description: The comma-separated list of reviewers to the new pull request.
  team-reviewers:
    description: The comma-separated list of team reviewers to the new pull request.
  labels:
    description: The comma-separated list of labels to the new pull request.
runs:
  using: 'node12'
  main: 'dist/bin/index.js'
