# Will be triggered either by 'pushing any tag' or 'manual trigger' with additional inputs
name: >-
  manual dispatch

on:
  # Run by manual trigger
  workflow_dispatch:
    inputs:
      version_type:
        description: >-
          The type of the semver version. Accepted inputs: major, minor, patch.
        required: true
        default: patch
      prerelease:
        description: >-
          A boolean indicator for creating a prerelease. GitHub 'pre-release' flag will also be set
          accordingly. Accepted inputs: true, false.
        required: false
        default: 'false'
      pre_id:
        description: >-
          A valid semver pre-release id to bump version to a pre-release version with the specific id.
        required: false
      pr-template-uri:
        description: >-
          The FQDN of the uri of the pull request template to be used. Template format can be
          found in: examples.
        required: false
      pr-base-branch:
        description: >-
          The base branch that the pull request is issued against.
        required: true
        default: main
      pr-update-if-exist:
        description: >-
          A boolean indicator for the behavior of re-issuing a pull request from the same branch
          to the same base. If set 'true', it will update the pull request,
          otherwise, action will fail.
        required: true
        default: 'true'
jobs:
  main_job:
    runs-on: ubuntu-latest
    name: A test job
    steps:
      - name: versioning pr
        id: versioning-pr
        uses: JaydenLiang/github-actions-versioning-pr@1.0.1-dev.6
        with:
          version-type: ${{ github.event.inputs.version-type }}
          prerelease: ${{ github.event.inputs.prerelease }}
          pre_id: ${{ github.event.inputs.pre_id }}
          pr-template-uri: ${{ github.event.inputs.pr-template-uri }}
          pr-base-branch: ${{ github.event.inputs.pr-base-branch }}
          pr-update-if-exist: ${{ github.event.inputs.pr-update-if-exist }}
      # Use the output from the `versioning-pr` step
      - name: Get the versioning-pr output
        run: |
          echo "The version-type was ${{ steps.['versioning-pr'].outputs['version-type'] }}"
          echo "The prerelease was ${{ steps.['versioning-pr'].outputs['prerelease'] }}"
          echo "The pre_id was ${{ steps.['versioning-pr'].outputs['pre_id'] }}"
          echo "The pr-template-uri was ${{ steps.['versioning-pr'].outputs['pr-template-uri'] }}"
          echo "The pr-base-branch was ${{ steps.['versioning-pr'].outputs['pr-base-branch'] }}"
          echo "The pr-title was ${{ steps.['versioning-pr'].outputs['pr-title'] }}"
          echo "The pr-body was ${{ steps.['versioning-pr'].outputs['pr-body'] }}"
          echo "The pr-reviewers was ${{ steps.['versioning-pr'].outputs['pr-reviewers'] }}"
          echo "The pr-team-reviewers was ${{ steps.['versioning-pr'].outputs['pr-team-reviewers'] }}"
          echo "The pr-labels was ${{ steps.['versioning-pr'].outputs['pr-labels'] }}"
          echo "The pr-update-if-exist was ${{ steps.['versioning-pr'].outputs['pr-update-if-exist'] }}"
