# Will be triggered either by 'pushing any tag' or 'manual trigger' with additional inputs
name: >-
  manual dispatch

on:
  # Run by manual trigger
  workflow_dispatch:
    inputs:
      version-type:
        description: >-
          The type of the semver version. Accepted inputs: major, minor, patch.
        required: true
        default: patch
      prerelease:
        description: >-
          A boolean indicator for creating a prerelease. GitHub 'pre-release' flag will also be set
          accordingly. Accepted inputs: true, false.
        required: false
        default: 'false'
      pre-id:
        description: >-
          A valid semver pre-release id to bump version to a pre-release version with the specific id.
        required: false
      pr-template-uri:
        description: >-
          The location (relative to the project rool) of the pull request template to be used. Template format can be
          found in: examples.
        required: false
        default: examples/pr-template.yml
      base-branch:
        description: >-
          The base branch that the pull request is issued against.
        required: true
        default: main
      pr-update-if-exist:
        description: >-
          A boolean indicator for the behavior of re-issuing a pull request from the same branch
          to the same base. If set 'true', it will update the pull request,
          otherwise, action will fail.
        required: true
        default: 'true'
      pr-create-draft:
        description: >-
          A boolean indicator for whether the pull request will be issued as a draft or not.
        required: false
        default: 'false'
jobs:
  main_job:
    runs-on: ubuntu-latest
    name: A test job
    steps:
      - name: versioning pr
        id: versioning-pr
        uses: JaydenLiang/github-actions-versioning-pr@1.0.1-dev.16
        with:
          base-branch: ${{ github.event.inputs.base-branch }}
          prerelease: ${{ github.event.inputs.prerelease }}
          pr-create-draft: ${{ github.event.inputs.pr-create-draft }}
          pr-update-if-exist: ${{ github.event.inputs.pr-update-if-exist }}
          pr-template-uri: ${{ github.event.inputs.pr-template-uri }}
      # Use the output from the `versioning-pr` step
      - name: Get the versioning-pr output
        run: |
          echo "The base-branch was ${{ steps['versioning-pr'].outputs['base-branch'] }}"
          echo "The head-branch was ${{ steps['versioning-pr'].outputs['head-branch'] }}"
          echo "The base-version was ${{ steps['versioning-pr'].outputs['base-version'] }}"
          echo "The head-version was ${{ steps['versioning-pr'].outputs['head-version'] }}"
          echo "The is-prerelease was ${{ steps['versioning-pr'].outputs['is-prerelease'] }}"
          echo "The pull-request-url was ${{ steps['versioning-pr'].outputs['pull-request-url'] }}"
